### ISSUE TITLE
PyTorch version of clean restricted ImageNet

### ISSUE THREAD

**Issue by amodas** [MadryLab/robust-features-code#5]
Hello,

First of all, thanks for the very nice work!

The provided pretrained networks on restricted ImageNet require tensorflow, but unfortunately I am a PyTorch user...

I have found the robust model from your other releases (ie [here](https://github.com/MadryLab/robust_representations)), but I would like to ask if a PyTorch version of a clean pretrained model on restricted ImageNet exists.

Thank you in advance!

**Comment by dtsip** [comment]
Hi, unfortunately we don't have a pretrained model released. You can train one relatively easily using our recently release `robustness` library https://github.com/MadryLab/robustness .
